### ISSUE TITLE
Update to Python3

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/py-mapzen-whosonfirst-spatial#11]
Update to Python3. Example:

https://github.com/whosonfirst/py-mapzen-whosonfirst-spatial/blob/master/mapzen/whosonfirst/spatial/postgres.py#L233

```
filters.has_key("wof:is_ceased")
```
 
would now be

```
"wof:is_ceased" in filters
```

**Comment by thisisaaronland** [comment]
Fixed in `v2.0.1` release.
