### ISSUE TITLE
PostGIS Windows instructions

### ISSUE THREAD

**Issue by stantond** [whosonfirst/py-mapzen-whosonfirst-spatial#4]
Had some trouble. Given the postgres user only exists in postgres, it was easier to use the [Windows installer](http://www.enterprisedb.com/products-services-training/pgdownload#windows), use Stack Builder to install PostGIS, add the `bin` folder to `PATH`, and then

```
psql -U postgres
CREATE DATABASE whosonfirst;
\connect whosonfirst
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE TABLE whosonfirst (id BIGINT PRIMARY KEY, parent_id BIGINT, placetype VARCHAR, properties TEXT, geom GEOGRAPHY(MULTIPOLYGON, 4326), centroid GEOGRAPHY(POINT, 4326));
CREATE INDEX by_geom ON whosonfirst USING GIST(geom);
CREATE INDEX by_placetype ON whosonfirst (placetype);
VACUUM ANALYZE;
```

I'm new at this. I can add it to the doc if that's helpful, but there's probably a more efficient Windows-friendly way to do this.

I'm on Windows 10 using Python 3.5 and PostgreSQL 9.5.

**Comment by thisisaaronland** [comment]
Closing this (for now) per: https://github.com/whosonfirst/py-mapzen-whosonfirst-spatial#mapzenwhosonfirstspatialpostgrespostgis
