### ISSUE TITLE
Dependency Shapely needs to be installed differently on Windows

### ISSUE THREAD

**Issue by stantond** [whosonfirst/py-mapzen-whosonfirst-spatial#5]
On Windows, Shapely needs to be installed with `pip install path_to_package` with a package [downloaded from here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely).

I'm on Windows 10 using Python 3.5.

**Comment by thisisaaronland** [comment]
Is there a way to indicate / specify these requirements in a standard `setup.py` file? I don't have any substantial experience dealing with packaging under Windows.

**Comment by stantond** [comment]
Honestly, I have no idea. Without something better, I'd pop it in the readme as a prerequisite for Windows users so that setup.py won't fail.

**Comment by thisisaaronland** [comment]
Closing this (for now) per: https://github.com/whosonfirst/py-mapzen-whosonfirst-spatial#caveats
